name: deploy function to gcs
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-job:
    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: create archive
        run: zip -r hotel-dataseed.zip .
      - name: gcloud auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/${{ secrets.project_id }}/locations/global/workloadIdentityPools/github/providers/hotel-connector
      - name: set up gcloud sdk
        uses: google-github-actions/setup-gcloud@v2
      - name: copy archive
        run: gcloud storage cp hotel-dataseed.zip gs://${{ secrets.project_id }}-cloud-functions/
